language: node_js
node_js:
- 10.15.0
branches:
  only:
  - master # whatever you want

install: npm install

notifications:
  email:
    recipients:
      - rosyworld@126.com #email
    on_success: change
    on_failure: always

before_script:
- git config --global user.name "rosyworld"
- git config --global user.email "rosyworld@126.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml
- sed -i "s/__VISITORS_APPID__/${__APP_ID__}/" _config.yml
- sed -i "s/__VISITORS_APPKEY__/${__APP_KEY__}/" _config.yml

script: npm run build

after_success:
- hexo deploy
